name: Deploy to Production
concurrency:
  group: production-deploy
  cancel-in-progress: true
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/home-site
            git pull origin master
            cd nextjs
            docker build -t nextjs-image .
            docker stop nextjs-container || true
            docker rm nextjs-container || true
            docker run -d --name nextjs-container -p 3000:3000 nextjs-image
